spring.application.name=microservice-front
server.port=8082
server.forward-headers-strategy=framework

app.urls.patients=http://gateway:8080/api/patients
app.urls.notes=http://gateway:8080/api/notes
app.urls.assessment=http://gateway:8080/api/assessment

