spring.application.name=microservice-notes
server.port=8083
# Database configuration
spring.mongodb.host=mongodb
spring.mongodb.port=27017
spring.mongodb.username=root
spring.mongodb.password=root
spring.mongodb.authentication-database=admin
spring.mongodb.database=notesdb
